name: working with inputs
on:
  workflow_dispatch:
    inputs:
      debug:
        description: 'Debug mode'
        required: true
        type: boolean
      version:
        description: 'Version to deploy'
        required: true
        default: 'latest'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
        - name: Display inputs
          run: echo "Debug mode ${{ inputs.tag }}"
  build:
    runs-on: ubuntu-latest
    steps:
        - name: Display inputs
          run: echo "Debug mode ${{ inputs.version }}"

